paths:
  /api/tvdb/search:
    get:
      tags:
        - TVDB
      summary: Find a show
      operationId: tvdbSearch
      parameters:
        - name: showTitle
          in: query
          required: true
          description: Show name
          example: The Flash
          schema:
            type: string
      produces:
        - application/json
      responses:
        200:
          description: OK
          content:
            application/json: &findResponse
              schema:
                $ref: "#/components/schemas/FindResponse"
            application/ld+json: *findResponse
            text/html: *findResponse
  /api/tvdb/series/ingest:
    post:
      tags:
        - TVDB
      summary: Ingest Series
      operationId: tvdbIngestSeries
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Criteria'
      responses:
        201:
          description: Created
        400:
          description: Bad request
components:
  schemas:
    FindResponse:
      type: array
      items:
        type: object
        properties:
          seriesId:
            type: integer
          title:
            type: string
          year:
            type: integer
    Criteria:
      type: object
      properties:
        seriesId:
          type: integer
        season:
          type: integer
          default: 1
        episode:
          type: integer
          default: 1