name: Docker Image CI

on:
  push:
    branches:
      - main  # Change this to your desired branch

permissions:
  contents: read
  packages: write  # Required to push to GitHub Container Registry
  id-token: write  # Needed for authentication

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
            DATE_TIME="$(date +'%Y.%m.%d.%H.%M')"
            echo "DATE_TIME=$DATE_TIME" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/cookbook:$DATE_TIME -f docker/php/Dockerfile.prod . --platform=linux/amd64

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tvwatchlist:$DATE_TIME
          docker tag ghcr.io/${{ github.repository_owner }}/tvwatchlist:$DATE_TIME ghcr.io/${{ github.repository_owner }}/tvwatchlist:latest
          docker push ghcr.io/${{ github.repository_owner }}/tvwatchlist:latest
