name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t tvwatchlist:latest -f docker/php/Dockerfile.prod . --platform=linux/amd64

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker tag tvwatchlist:latest ${{ secrets.DOCKER_USERNAME }}/tvwatchlist:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/tvwatchlist:latest
