name: PHP Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      env:
        WORKFLOW_RUN_URL: ${{ steps.trigger.outputs.workflow_run_url }}
        WORKFLOW_RUN_STATUS: ${{ job.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, zip, mongodb, xdebug
          coverage: pcov
          ini-values: opcache.enable=1

      - name: Install dependencies
        run: |
          cd app
          composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: |
          cd app
          vendor/bin/phpunit --coverage-text --colors=never --log-junit test-results/junit.xml
      
      

      - name: Trigger
        id: trigger
        run: echo "workflow_run_url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
