name: Update README

on:
  workflow_run:
    workflows: ["PHP Tests"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Execute Update Script
        run: bash update-readme.sh

      - name: Remove old README
        run: rm README.bak

      - name: Commit and push if changed
        run: |
          git diff --quiet || git commit -am "[skip ci] Update README.md" && git push
