name: Update README
on:
  workflow_run:
    workflows: ["Ghaction test"]
    types:
      - completed
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get Last Run Info
        run: |
          # Get the URL and status of the last run for a specific workflow
          WORKFLOW_NAME="PHP Tests"
          REPO_OWNER="aussieveen"
          REPO_NAME="tvwatchlist"
          WORKFLOW_RUN_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/runs?event=workflow_run" \
          | jq -r '.workflow_runs[0].html_url')
          WORKFLOW_RUN_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/runs?event=workflow_run" \
          | jq -r '.workflow_runs[0].conclusion')
          echo "WORKFLOW_RUN_URL=$WORKFLOW_RUN_URL" >> $GITHUB_ENV
          echo "WORKFLOW_RUN_STATUS=WORKFLOW_RUN_STATUS" >> $GITHUB_ENV

      - name: Execute Update Script
        run: bash update-readme.sh

      - name: Remove old README
        run: rm README.bak

      - name: Commit and push if changed
        run: |
          git diff --quiet || git commit -am "[skip ci] Update README.md" && git push
